name: 'QualityMax Test Runner'
description: 'Run AI-powered E2E tests in your CI/CD pipeline. Zero configuration, instant results.'
author: 'QualityMax'

branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  api-key:
    description: 'QualityMax API key (get it from app.qamax.co/settings/api)'
    required: true
  project-id:
    description: 'QualityMax project ID (optional if project-name provided or repo auto-detected)'
    required: false
  project-name:
    description: 'QualityMax project name (alternative to project-id)'
    required: false
  test-suite:
    description: 'Test suite to run: all, smoke, regression, or custom'
    required: false
    default: 'all'
  test-ids:
    description: 'Comma-separated list of specific test IDs to run (for custom suite)'
    required: false
  base-url:
    description: 'Base URL to test against (overrides project default)'
    required: false
  browser:
    description: 'Browser to use: chromium, firefox, or webkit'
    required: false
    default: 'chromium'
  headless:
    description: 'Run tests in headless mode'
    required: false
    default: 'true'
  timeout-minutes:
    description: 'Maximum execution time in minutes'
    required: false
    default: '30'
  fail-on-test-failure:
    description: 'Fail the workflow if any tests fail'
    required: false
    default: 'true'
  post-pr-comment:
    description: 'Post test results as a PR comment'
    required: false
    default: 'true'
  mode:
    description: 'Action mode: run (default) or seed (bootstrap tests via AI discovery)'
    required: false
    default: 'run'
  auto-discover:
    description: 'Auto-discover test scenarios in seed mode'
    required: false
    default: 'true'
  max-seed-tests:
    description: 'Maximum number of tests to generate in seed mode (1-10)'
    required: false
    default: '3'
  seed-descriptions:
    description: 'Newline-separated test descriptions for seed mode (overrides auto-discover)'
    required: false

outputs:
  execution-id:
    description: 'Unique execution ID for this test run'
  status:
    description: 'Final status: passed, failed, cancelled, timeout'
  total-tests:
    description: 'Total number of tests run'
  passed-tests:
    description: 'Number of tests that passed'
  failed-tests:
    description: 'Number of tests that failed'
  duration-seconds:
    description: 'Total execution time in seconds'
  report-url:
    description: 'URL to the full test report'
  summary-markdown:
    description: 'Pre-formatted markdown summary for PR comments'
  tests-created:
    description: 'Number of tests created in seed mode'
  tests-skipped:
    description: 'Number of tests skipped in seed mode (already existed)'
  seed-message:
    description: 'Summary message from seed operation'

runs:
  using: 'node20'
  main: 'dist/index.js'
